version: '2'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bpuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'FknSC6GNAQ'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'TRnF7ssy47'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - BP_generated_app-db:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - .:/app
    container_name: BP_generated_app
    tty: true
volumes:
  BP_generated_app-db: