export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const UPDATE_USER = "UPDATE_USER";

export const TOAST_INFO_SHOW = "TOAST_INFO_SHOW";
export const TOAST_ERROR_SHOW = "TOAST_INFO_ERROR";
export const TOAST_HIDE = "TOAST_HIDE";

export const LOADING_SHOW = "LOADING_SHOW";
export const LOADING_HIDE = "LOADING_HIDE";

export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";

export const SIDEBAR_SHOW = "SIDEBAR_SHOW";
export const SIDEBAR_HIDE = "SIDEBAR_HIDE";

export const USER_LOAD_LIST = "USER_LOAD_LIST";
export const USER_LOAD_DETAIL = "USER_LOAD_DETAIL";

export const TODO_LOAD_LIST = "TODO_LOAD_LIST";
export const TODO_LOAD_DETAIL = "TODO_LOAD_DETAIL";

export const MASTER_LOAD_LIST = "MASTER_LOAD_LIST";

export const SIDEBAR_HIGHLIGHT = "SIDEBAR_HIGHLIGHT";
